services:
  postgres:
    image: postgres:15
    container_name: scd_postgres
    environment:
      POSTGRES_DB: datawarehouse
      POSTGRES_USER: dw_user
      POSTGRES_PASSWORD: dw_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    networks:
      - scd_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: scd_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@datawarehouse.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - scd_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  scd_network:
    driver: bridge